#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
#nm-applet &
sxhkd &

xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate right --output DP-0 --off --output DP-1 --off --output DP-2 --primary --mode 2560x1440 --rate 165 --pos 1080x240 --rotate normal --output DP-3 --off --output HDMI-1 --off --output USB-C-0 --off &

$HOME/.config/polybar/launch.sh &
picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &
nitrogen --restore &
dunst &
playerctld daemon &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-2 -d 1 2 3 4 
bspc monitor HDMI-0 -d 5 6
#    ﭮ   
# Border
bspc config focused_border_color        "#DDB6F2"
bspc config normal_border_color         "#4C566A"
bspc config active_border_color         "#4C566A"

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a code desktop='^2'
bspc rule -a steam desktop='^5'
bspc rule -a cider desktop='^7'
#bspc rule -a discord desktop='^7'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^1'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Screenkey manage=off

bspc rule -a Emacs state=tiled
